name: Build and Deploy to Docker Hub

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: ./gradlew buildImage

      - name: Tag Docker image
        run: |
          image_tag=${GITHUB_REF#refs/tags/}
          docker tag nuecagram-docker-image:latest user/repository:$image_tag
          docker tag nuecagram-docker-image:latest user/repository:latest
          if [ $? -ne 0 ]; then
            echo "Failed to tag Docker image."
            exit 1
          fi
      - name: Push Docker image
        run: |
          image_tag=${GITHUB_REF#refs/tags/}
          docker push user/repository:$image_tag
          docker push user/repository:latest
          if [ $? -ne 0 ]; then
            echo "Failed to push Docker image."
            exit 1
          fi

      - name: Update version in build.gradle.kts
        run: |
          version=${GITHUB_REF#refs/tags/}
          echo "$version" > version.txt
          if [ $? -ne 0 ]; then
            echo "Failed to update version.txt."
            exit 1
          fi
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add build.gradle.kts
          git commit -m "Update version to $version"
          git push origin main
          if [ $? -ne 0 ]; then
            echo "Failed to push updated version to Git."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
