name: Ktor CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: action/checkout@v3
      - name: Setup JDK17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          overwrite-settings: false
      - run: ./gradlew assemble


