name: Lint

on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup JDK17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          overwrite-settings: false
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Run Lint
        run: ./gradlew lintKotlin
      - name: Run Tests
        run: ./gradlew test


